timepix:
   pc_ip : '192.168.1.1'
   tpx_ip : '192.168.1.10'
   sophy_config : 'path_to_sophy_config'
trainID:
   connected: False
   device : '/dev/ttyUSB0'
src_ip_port:
   - '192.168.1.1'
   - 8192
tcp_channel:
   - '127.0.0.1'
   - 5056