timepix:
   pc_ip : '192.168.1.1'
   tpx_ip : '192.168.1.10'
   sophy_config : 'path_to_sophy_config'
   remote_processing_host: '131.169.168.130:13049'
trainID:
   connected: False
   device : '/dev/ttyUSB0'
src_ip_port:
   - '192.168.1.1'
   - 8192
api_channel:
   ip: '127.0.0.1'
   port: 5056