timepix:
   tpx_ip: '192.168.1.1'
   tpx_ctrl_tcp_port: 50000
   tpx_data_udp_port: 8192
   sophy_config : 'path_to_sophy_config'
   remote_processing_host: '131.169.168.130:13049'
   camera_generation: 3
trainID:
   connected: False
   device : '/dev/ttyUSB0'
api_channel:
   ip: '127.0.0.1'
   port: 5056