name: 'electrons'
timepix:
   pc_ip : '192.168.1.1'
   pc_port: 5566
   tpx_ip : '192.168.1.10'
   sophy_config : '/home/cfelcmi/timepix/ElectronTPX_IKrum150.spx'
trainID:
   connected: False
   device : '/dev/ttyUSB0'
tango_api:
   port: 9993
