name: 'ions'
timepix:
   pc_ip : '192.168.1.1'
   udp_port: 11113
   tpx_ip : '192.168.1.11'
   sophy_config : '/home/cfelcmi/timepix/10Gb2_50V_IKrum150.spx'
trainID:
   connected: False
   device : '/dev/ttyUSB0'
tango_api:
   port: 9994
tcpchannel:
   ip : '127.0.0.1'
   port: 5056