timepix:
   pc_ip : '192.168.1.1'
   pc_port: 11113
   tpx_ip : '192.168.1.15'
   sophy_config : 'path_to_sophy_config'
trainID:
   connected: False
   device : '/dev/ttyUSB0'
tango_api:
   port: 9994
