# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daqconfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 300)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.path_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.path_name.setObjectName("path_name")
        self.horizontalLayout_4.addWidget(self.path_name)
        self.openpath = QtWidgets.QPushButton(self.groupBox_3)
        self.openpath.setObjectName("openpath")
        self.horizontalLayout_4.addWidget(self.openpath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.file_prefix = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_prefix.setObjectName("file_prefix")
        self.horizontalLayout_5.addWidget(self.file_prefix)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.raw_enable = QtWidgets.QCheckBox(self.groupBox_3)
        self.raw_enable.setObjectName("raw_enable")
        self.horizontalLayout_9.addWidget(self.raw_enable)
        self.blob_enable = QtWidgets.QCheckBox(self.groupBox_3)
        self.blob_enable.setChecked(True)
        self.blob_enable.setObjectName("blob_enable")
        self.horizontalLayout_9.addWidget(self.blob_enable)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.exposure_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.exposure_time.setObjectName("exposure_time")
        self.horizontalLayout_8.addWidget(self.exposure_time)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.acq_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.acq_time.setObjectName("acq_time")
        self.horizontalLayout_6.addWidget(self.acq_time)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.display_rate = QtWidgets.QSlider(self.groupBox)
        self.display_rate.setMinimum(5)
        self.display_rate.setMaximum(30)
        self.display_rate.setOrientation(QtCore.Qt.Horizontal)
        self.display_rate.setInvertedAppearance(False)
        self.display_rate.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.display_rate.setTickInterval(5)
        self.display_rate.setObjectName("display_rate")
        self.horizontalLayout_2.addWidget(self.display_rate)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.event_count = QtWidgets.QLineEdit(self.groupBox)
        self.event_count.setInputMask("")
        self.event_count.setObjectName("event_count")
        self.horizontalLayout_3.addWidget(self.event_count)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.reset_plots = QtWidgets.QPushButton(self.groupBox)
        self.reset_plots.setObjectName("reset_plots")
        self.verticalLayout.addWidget(self.reset_plots)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.text_status = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_status.setFont(font)
        self.text_status.setObjectName("text_status")
        self.horizontalLayout.addWidget(self.text_status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.start_acq = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_acq.sizePolicy().hasHeightForWidth())
        self.start_acq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_acq.setFont(font)
        self.start_acq.setObjectName("start_acq")
        self.horizontalLayout.addWidget(self.start_acq)
        self.end_acq = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_acq.sizePolicy().hasHeightForWidth())
        self.end_acq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.end_acq.setFont(font)
        self.end_acq.setObjectName("end_acq")
        self.horizontalLayout.addWidget(self.end_acq)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "Acquisition"))
        self.label_6.setText(_translate("Form", "Path"))
        self.openpath.setText(_translate("Form", "Open"))
        self.label_7.setText(_translate("Form", "Prefix:"))
        self.file_prefix.setText(_translate("Form", "test_"))
        self.label_5.setText(_translate("Form", "Storage:"))
        self.raw_enable.setText(_translate("Form", "Raw"))
        self.blob_enable.setText(_translate("Form", "Blob"))
        self.label_10.setText(_translate("Form", "Max Exposure:"))
        self.exposure_time.setText(_translate("Form", "4"))
        self.label_11.setText(_translate("Form", "us"))
        self.label_8.setText(_translate("Form", "Acquisition Time:"))
        self.acq_time.setText(_translate("Form", "-1"))
        self.label_9.setText(_translate("Form", "s"))
        self.groupBox.setTitle(_translate("Form", "Viewer Config"))
        self.label.setText(_translate("Form", "Display Update (Hz)"))
        self.label_2.setText(_translate("Form", "5"))
        self.label_3.setText(_translate("Form", "30"))
        self.label_4.setText(_translate("Form", "Event Count:"))
        self.event_count.setText(_translate("Form", "-1"))
        self.reset_plots.setText(_translate("Form", "Reset Plots"))
        self.label_12.setText(_translate("Form", "Status:"))
        self.text_status.setText(_translate("Form", "Live"))
        self.start_acq.setText(_translate("Form", "Start Acquisition"))
        self.end_acq.setText(_translate("Form", "Stop Acquisition"))

