# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acqconfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(666, 388)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.path_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.path_name.setObjectName("path_name")
        self.horizontalLayout_4.addWidget(self.path_name)
        self.openpath = QtWidgets.QPushButton(self.groupBox_3)
        self.openpath.setObjectName("openpath")
        self.horizontalLayout_4.addWidget(self.openpath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.file_prefix = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_prefix.setObjectName("file_prefix")
        self.horizontalLayout_5.addWidget(self.file_prefix)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.startindex = QtWidgets.QLineEdit(self.groupBox_3)
        self.startindex.setObjectName("startindex")
        self.horizontalLayout_12.addWidget(self.startindex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.write_raw = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_raw.setObjectName("write_raw")
        self.horizontalLayout_9.addWidget(self.write_raw)
        self.write_pixels = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_pixels.setObjectName("write_pixels")
        self.horizontalLayout_9.addWidget(self.write_pixels)
        self.write_blob = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_blob.setChecked(True)
        self.write_blob.setObjectName("write_blob")
        self.horizontalLayout_9.addWidget(self.write_blob)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.acq_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.acq_time.setObjectName("acq_time")
        self.horizontalLayout_6.addWidget(self.acq_time)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.repeat_value = QtWidgets.QLineEdit(self.groupBox_3)
        self.repeat_value.setObjectName("repeat_value")
        self.horizontalLayout_11.addWidget(self.repeat_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.display_rate = QtWidgets.QSlider(self.groupBox)
        self.display_rate.setMinimum(5)
        self.display_rate.setMaximum(30)
        self.display_rate.setOrientation(QtCore.Qt.Horizontal)
        self.display_rate.setInvertedAppearance(False)
        self.display_rate.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.display_rate.setTickInterval(5)
        self.display_rate.setObjectName("display_rate")
        self.horizontalLayout_2.addWidget(self.display_rate)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.event_count = QtWidgets.QLineEdit(self.groupBox)
        self.event_count.setInputMask("")
        self.event_count.setObjectName("event_count")
        self.horizontalLayout_3.addWidget(self.event_count)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.reset_plots = QtWidgets.QPushButton(self.groupBox)
        self.reset_plots.setObjectName("reset_plots")
        self.verticalLayout.addWidget(self.reset_plots)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "Acquisition"))
        self.label_6.setText(_translate("Form", "Path"))
        self.openpath.setText(_translate("Form", "Open"))
        self.label_7.setText(_translate("Form", "Prefix:"))
        self.file_prefix.setText(_translate("Form", "test_"))
        self.label_14.setText(_translate("Form", "Index"))
        self.startindex.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "Storage:"))
        self.write_raw.setText(_translate("Form", "Raw"))
        self.write_pixels.setText(_translate("Form", "Pixels"))
        self.write_blob.setText(_translate("Form", "Blob"))
        self.label_8.setText(_translate("Form", "Acquisition Time:"))
        self.acq_time.setText(_translate("Form", "10"))
        self.label_9.setText(_translate("Form", "s"))
        self.label_13.setText(_translate("Form", "No of Files"))
        self.repeat_value.setText(_translate("Form", "1"))
        self.groupBox.setTitle(_translate("Form", "Viewer Config"))
        self.label.setText(_translate("Form", "Display Update (Hz)"))
        self.label_2.setText(_translate("Form", "5"))
        self.label_3.setText(_translate("Form", "30"))
        self.label_4.setText(_translate("Form", "Event Count:"))
        self.event_count.setText(_translate("Form", "-1"))
        self.reset_plots.setText(_translate("Form", "Reset Plots"))

