# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymepixviewer\panels\ui\acqconfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(288, 691)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.bias_voltage = QtWidgets.QSpinBox(self.groupBox_3)
        self.bias_voltage.setPrefix("")
        self.bias_voltage.setMinimum(12)
        self.bias_voltage.setMaximum(104)
        self.bias_voltage.setProperty("value", 50)
        self.bias_voltage.setObjectName("bias_voltage")
        self.horizontalLayout_16.addWidget(self.bias_voltage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.fine_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.fine_threshold.setPrefix("")
        self.fine_threshold.setMaximum(255.0)
        self.fine_threshold.setSingleStep(0.5)
        self.fine_threshold.setObjectName("fine_threshold")
        self.horizontalLayout_18.addWidget(self.fine_threshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.coarse_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.coarse_threshold.setPrefix("")
        self.coarse_threshold.setMaximum(1.19)
        self.coarse_threshold.setSingleStep(0.08)
        self.coarse_threshold.setObjectName("coarse_threshold")
        self.horizontalLayout_19.addWidget(self.coarse_threshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.path_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.path_name.setObjectName("path_name")
        self.horizontalLayout_4.addWidget(self.path_name)
        self.openpath = QtWidgets.QPushButton(self.groupBox_3)
        self.openpath.setObjectName("openpath")
        self.horizontalLayout_4.addWidget(self.openpath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.file_prefix = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_prefix.setObjectName("file_prefix")
        self.horizontalLayout_5.addWidget(self.file_prefix)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.startindex = QtWidgets.QSpinBox(self.groupBox_3)
        self.startindex.setMaximum(99999)
        self.startindex.setObjectName("startindex")
        self.horizontalLayout_12.addWidget(self.startindex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.write_raw = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_raw.setChecked(True)
        self.write_raw.setObjectName("write_raw")
        self.horizontalLayout.addWidget(self.write_raw)
        self.write_pixels = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_pixels.setObjectName("write_pixels")
        self.horizontalLayout.addWidget(self.write_pixels)
        self.write_tof = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_tof.setObjectName("write_tof")
        self.horizontalLayout.addWidget(self.write_tof)
        self.write_blob = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_blob.setChecked(False)
        self.write_blob.setObjectName("write_blob")
        self.horizontalLayout.addWidget(self.write_blob)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.acq_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.acq_time.setObjectName("acq_time")
        self.horizontalLayout_6.addWidget(self.acq_time)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.repeat_value = QtWidgets.QSpinBox(self.groupBox_3)
        self.repeat_value.setMinimum(1)
        self.repeat_value.setMaximum(99999)
        self.repeat_value.setProperty("value", 1)
        self.repeat_value.setObjectName("repeat_value")
        self.horizontalLayout_11.addWidget(self.repeat_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.mode_box = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_box.sizePolicy().hasHeightForWidth())
        self.mode_box.setSizePolicy(sizePolicy)
        self.mode_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mode_box.setIconSize(QtCore.QSize(16, 16))
        self.mode_box.setObjectName("mode_box")
        self.mode_box.addItem("")
        self.mode_box.addItem("")
        self.mode_box.addItem("")
        self.horizontalLayout_17.addWidget(self.mode_box)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.display_rate = QtWidgets.QSlider(self.groupBox)
        self.display_rate.setMinimum(5)
        self.display_rate.setMaximum(30)
        self.display_rate.setOrientation(QtCore.Qt.Horizontal)
        self.display_rate.setInvertedAppearance(False)
        self.display_rate.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.display_rate.setTickInterval(5)
        self.display_rate.setObjectName("display_rate")
        self.horizontalLayout_2.addWidget(self.display_rate)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.framelayout = QtWidgets.QWidget(self.groupBox)
        self.framelayout.setObjectName("framelayout")
        self.frametimelayout = QtWidgets.QHBoxLayout(self.framelayout)
        self.frametimelayout.setObjectName("frametimelayout")
        self.label_16 = QtWidgets.QLabel(self.framelayout)
        self.label_16.setObjectName("label_16")
        self.frametimelayout.addWidget(self.label_16)
        self.frame_time = QtWidgets.QLineEdit(self.framelayout)
        self.frame_time.setInputMask("")
        self.frame_time.setObjectName("frame_time")
        self.frametimelayout.addWidget(self.frame_time)
        self.time_multi = QtWidgets.QComboBox(self.framelayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_multi.sizePolicy().hasHeightForWidth())
        self.time_multi.setSizePolicy(sizePolicy)
        self.time_multi.setMaximumSize(QtCore.QSize(70, 16777215))
        self.time_multi.setIconSize(QtCore.QSize(16, 16))
        self.time_multi.setObjectName("time_multi")
        self.time_multi.addItem("")
        self.time_multi.addItem("")
        self.frametimelayout.addWidget(self.time_multi)
        self.verticalLayout.addWidget(self.framelayout)
        self.eventwidget = QtWidgets.QWidget(self.groupBox)
        self.eventwidget.setObjectName("eventwidget")
        self.eventlayout = QtWidgets.QHBoxLayout(self.eventwidget)
        self.eventlayout.setObjectName("eventlayout")
        self.label_4 = QtWidgets.QLabel(self.eventwidget)
        self.label_4.setObjectName("label_4")
        self.eventlayout.addWidget(self.label_4)
        self.event_count = QtWidgets.QLineEdit(self.eventwidget)
        self.event_count.setInputMask("")
        self.event_count.setObjectName("event_count")
        self.eventlayout.addWidget(self.event_count)
        self.verticalLayout.addWidget(self.eventwidget)
        self.reset_plots = QtWidgets.QPushButton(self.groupBox)
        self.reset_plots.setObjectName("reset_plots")
        self.verticalLayout.addWidget(self.reset_plots)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "Acquisition"))
        self.label_17.setText(_translate("Form", "Bias Voltage"))
        self.bias_voltage.setSuffix(_translate("Form", " V"))
        self.label_19.setText(_translate("Form", "Fine Threshold"))
        self.fine_threshold.setSuffix(_translate("Form", "mV"))
        self.label_20.setText(_translate("Form", "Coarse Threshold"))
        self.coarse_threshold.setSuffix(_translate("Form", "V"))
        self.label_6.setText(_translate("Form", "Path"))
        self.openpath.setText(_translate("Form", "Open"))
        self.label_7.setText(_translate("Form", "Prefix:"))
        self.file_prefix.setText(_translate("Form", "test_"))
        self.label_14.setText(_translate("Form", "Index"))
        self.label_5.setText(_translate("Form", "Storage:"))
        self.write_raw.setText(_translate("Form", "Raw"))
        self.write_pixels.setText(_translate("Form", "Pixels"))
        self.write_tof.setText(_translate("Form", "TOF"))
        self.write_blob.setText(_translate("Form", "Blob"))
        self.label_8.setText(_translate("Form", "Acquisition Time:"))
        self.acq_time.setText(_translate("Form", "10"))
        self.label_9.setText(_translate("Form", "s"))
        self.label_13.setText(_translate("Form", "No of Files"))
        self.groupBox.setTitle(_translate("Form", "Viewer Config"))
        self.label_18.setText(_translate("Form", "Mode:"))
        self.mode_box.setItemText(0, _translate("Form", "Time of Arrival Only"))
        self.mode_box.setItemText(1, _translate("Form", "Time of Flight Only"))
        self.mode_box.setItemText(2, _translate("Form", "Centroid"))
        self.label.setText(_translate("Form", "Display Update (Hz)"))
        self.label_2.setText(_translate("Form", "5"))
        self.label_3.setText(_translate("Form", "30"))
        self.label_16.setText(_translate("Form", "Frame time"))
        self.frame_time.setText(_translate("Form", "-1"))
        self.time_multi.setItemText(0, _translate("Form", "s"))
        self.time_multi.setItemText(1, _translate("Form", "ms"))
        self.label_4.setText(_translate("Form", "Event Count:"))
        self.event_count.setText(_translate("Form", "-1"))
        self.reset_plots.setText(_translate("Form", "Reset Plots"))

