# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymepixviewer\panels\ui\acqconfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(288, 691)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.bias_voltage = QtWidgets.QSpinBox(self.groupBox_3)
        self.bias_voltage.setPrefix("")
        self.bias_voltage.setMinimum(12)
        self.bias_voltage.setMaximum(104)
        self.bias_voltage.setProperty("value", 50)
        self.bias_voltage.setObjectName("bias_voltage")
        self.horizontalLayout_16.addWidget(self.bias_voltage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.fine_threshold = QtWidgets.QSpinBox(self.groupBox_3)
        self.fine_threshold.setPrefix("")
        self.fine_threshold.setMaximum(511)
        self.fine_threshold.setSingleStep(1)
        self.fine_threshold.setObjectName("fine_threshold")
        self.horizontalLayout_18.addWidget(self.fine_threshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.coarse_threshold = QtWidgets.QSpinBox(self.groupBox_3)
        self.coarse_threshold.setPrefix("")
        self.coarse_threshold.setMaximum(15)
        self.coarse_threshold.setSingleStep(1)
        self.coarse_threshold.setObjectName("coarse_threshold")
        self.horizontalLayout_19.addWidget(self.coarse_threshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.path_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.path_name.setObjectName("path_name")
        self.horizontalLayout_4.addWidget(self.path_name)
        self.openpath = QtWidgets.QPushButton(self.groupBox_3)
        self.openpath.setObjectName("openpath")
        self.horizontalLayout_4.addWidget(self.openpath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.file_prefix = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_prefix.setObjectName("file_prefix")
        self.horizontalLayout_5.addWidget(self.file_prefix)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.startindex = QtWidgets.QSpinBox(self.groupBox_3)
        self.startindex.setMaximum(99999)
        self.startindex.setObjectName("startindex")
        self.horizontalLayout_12.addWidget(self.startindex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.write_raw = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_raw.setChecked(True)
        self.write_raw.setObjectName("write_raw")
        self.horizontalLayout.addWidget(self.write_raw)
        self.write_pixels = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_pixels.setObjectName("write_pixels")
        self.horizontalLayout.addWidget(self.write_pixels)
        self.write_tof = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_tof.setObjectName("write_tof")
        self.horizontalLayout.addWidget(self.write_tof)
        self.write_blob = QtWidgets.QCheckBox(self.groupBox_3)
        self.write_blob.setChecked(False)
        self.write_blob.setObjectName("write_blob")
        self.horizontalLayout.addWidget(self.write_blob)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.acq_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.acq_time.setObjectName("acq_time")
        self.horizontalLayout_6.addWidget(self.acq_time)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.repeat_value = QtWidgets.QSpinBox(self.groupBox_3)
        self.repeat_value.setMinimum(1)
        self.repeat_value.setMaximum(99999)
        self.repeat_value.setProperty("value", 1)
        self.repeat_value.setObjectName("repeat_value")
        self.horizontalLayout_11.addWidget(self.repeat_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "Acquisition"))
        self.label_17.setText(_translate("Form", "Bias Voltage"))
        self.bias_voltage.setSuffix(_translate("Form", " V"))
        self.label_19.setText(_translate("Form", "Fine Threshold [0, 511]"))
        self.fine_threshold.setSuffix(_translate("Form", ""))
        self.label_20.setText(_translate("Form", "Coarse Threshold [0, 15]"))
        self.coarse_threshold.setSuffix(_translate("Form", ""))
        self.label_6.setText(_translate("Form", "Path"))
        self.openpath.setText(_translate("Form", "Open"))
        self.label_7.setText(_translate("Form", "Prefix:"))
        self.file_prefix.setText(_translate("Form", "test_"))
        self.label_14.setText(_translate("Form", "Index"))
        self.label_5.setText(_translate("Form", "Storage:"))
        self.write_raw.setText(_translate("Form", "Raw"))
        self.write_pixels.setText(_translate("Form", "Pixels"))
        self.write_tof.setText(_translate("Form", "TOF"))
        self.write_blob.setText(_translate("Form", "Blob"))
        self.label_8.setText(_translate("Form", "Acquisition Time:"))
        self.acq_time.setText(_translate("Form", "10"))
        self.label_9.setText(_translate("Form", "s"))
        self.label_13.setText(_translate("Form", "No of Files"))
