# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymepixviewer\panels\ui\viewerconfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.mode_box = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_box.sizePolicy().hasHeightForWidth())
        self.mode_box.setSizePolicy(sizePolicy)
        self.mode_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mode_box.setIconSize(QtCore.QSize(16, 16))
        self.mode_box.setObjectName("mode_box")
        self.mode_box.addItem("")
        self.mode_box.addItem("")
        self.mode_box.addItem("")
        self.horizontalLayout_17.addWidget(self.mode_box)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.display_rate = QtWidgets.QSlider(self.groupBox)
        self.display_rate.setMinimum(5)
        self.display_rate.setMaximum(30)
        self.display_rate.setOrientation(QtCore.Qt.Horizontal)
        self.display_rate.setInvertedAppearance(False)
        self.display_rate.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.display_rate.setTickInterval(5)
        self.display_rate.setObjectName("display_rate")
        self.horizontalLayout_2.addWidget(self.display_rate)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.framelayout = QtWidgets.QWidget(self.groupBox)
        self.framelayout.setObjectName("framelayout")
        self.frametimelayout = QtWidgets.QHBoxLayout(self.framelayout)
        self.frametimelayout.setObjectName("frametimelayout")
        self.label_16 = QtWidgets.QLabel(self.framelayout)
        self.label_16.setObjectName("label_16")
        self.frametimelayout.addWidget(self.label_16)
        self.frame_time = QtWidgets.QLineEdit(self.framelayout)
        self.frame_time.setInputMask("")
        self.frame_time.setObjectName("frame_time")
        self.frametimelayout.addWidget(self.frame_time)
        self.time_multi = QtWidgets.QComboBox(self.framelayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_multi.sizePolicy().hasHeightForWidth())
        self.time_multi.setSizePolicy(sizePolicy)
        self.time_multi.setMaximumSize(QtCore.QSize(70, 16777215))
        self.time_multi.setIconSize(QtCore.QSize(16, 16))
        self.time_multi.setObjectName("time_multi")
        self.time_multi.addItem("")
        self.time_multi.addItem("")
        self.frametimelayout.addWidget(self.time_multi)
        self.verticalLayout.addWidget(self.framelayout)
        self.eventwidget = QtWidgets.QWidget(self.groupBox)
        self.eventwidget.setObjectName("eventwidget")
        self.eventlayout = QtWidgets.QHBoxLayout(self.eventwidget)
        self.eventlayout.setObjectName("eventlayout")
        self.label_4 = QtWidgets.QLabel(self.eventwidget)
        self.label_4.setObjectName("label_4")
        self.eventlayout.addWidget(self.label_4)
        self.event_count = QtWidgets.QLineEdit(self.eventwidget)
        self.event_count.setInputMask("")
        self.event_count.setObjectName("event_count")
        self.eventlayout.addWidget(self.event_count)
        self.verticalLayout.addWidget(self.eventwidget)
        self.reset_plots = QtWidgets.QPushButton(self.groupBox)
        self.reset_plots.setObjectName("reset_plots")
        self.verticalLayout.addWidget(self.reset_plots)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Viewer Config"))
        self.label_18.setText(_translate("Form", "Mode:"))
        self.mode_box.setItemText(0, _translate("Form", "Time of Arrival Only"))
        self.mode_box.setItemText(1, _translate("Form", "Time of Flight Only"))
        self.mode_box.setItemText(2, _translate("Form", "Centroid"))
        self.label.setText(_translate("Form", "Display Update (Hz)"))
        self.label_2.setText(_translate("Form", "5"))
        self.label_3.setText(_translate("Form", "30"))
        self.label_16.setText(_translate("Form", "Frame time"))
        self.frame_time.setText(_translate("Form", "-1"))
        self.time_multi.setItemText(0, _translate("Form", "s"))
        self.time_multi.setItemText(1, _translate("Form", "ms"))
        self.label_4.setText(_translate("Form", "Event Count:"))
        self.event_count.setText(_translate("Form", "-1"))
        self.reset_plots.setText(_translate("Form", "Reset Plots"))
